[package]
name = "extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.15.6"
num-complex = { version = "0.4", optional = true }

[features]
default = []
complex = ["num-complex"]
